<?php

use example\Mutation\ExampleMutation;
use example\Query\ExampleQuery;
use example\Type\ExampleRelationType;
use example\Type\ExampleType;

return [
    'prefix' => 'graphql',
    'routes' => '{graphql_schema?}',
    'controllers' => \Rebing\GraphQL\GraphQLController::class . '@query',
    'middleware' => [],
    'route_group_attributes' => [],
    'default_schema' => 'default',
    'schemas' => [
        'default' => [
            'query' => [
                'users'         => App\GraphQL\Query\UserQuery::class,
                'organizations' => App\GraphQL\Query\OrganizationQuery::class,
                'categories'    => App\GraphQL\Query\CategoryQuery::class,
                'subcategories' => App\GraphQL\Query\SubcategoryQuery::class,
                'articles'      => App\GraphQL\Query\ArticleQuery::class,
                'figures'       => App\GraphQL\Query\ArticleFigureQuery::class,
                'publications'  => App\GraphQL\Query\PublicationQuery::class,
                'projects'      => App\GraphQL\Query\ProjectQuery::class,
                'challenges'    => App\GraphQL\Query\ChallengeQuery::class,
                'docs'          => App\GraphQL\Query\DocQuery::class,
                'seals'         => App\GraphQL\Query\SealQuery::class,
                'comments'      => App\GraphQL\Query\CommentQuery::class,
                'likes'         => App\GraphQL\Query\LikeQuery::class,
            ],
            'mutation' => [],
            'middleware' => [],
            'method' => ['post'],
        ],
        'authenticated' => [
            'query' => [
                'users'         => App\GraphQL\Query\UserQuery::class,
                'organizations' => App\GraphQL\Query\OrganizationQuery::class,
                'categories'    => App\GraphQL\Query\CategoryQuery::class,
                'subcategories' => App\GraphQL\Query\SubcategoryQuery::class,
                'articles'      => App\GraphQL\Query\ArticleQuery::class,
                'figures'       => App\GraphQL\Query\ArticleFigureQuery::class,
                'publications'  => App\GraphQL\Query\PublicationQuery::class,
                'projects'      => App\GraphQL\Query\ProjectQuery::class,
                'challenges'    => App\GraphQL\Query\ChallengeQuery::class,
                'docs'          => App\GraphQL\Query\DocQuery::class,
                'seals'         => App\GraphQL\Query\SealQuery::class,
                'comments'      => App\GraphQL\Query\CommentQuery::class,
                'likes'         => App\GraphQL\Query\LikeQuery::class,
            ],
            'mutation' => [
                'newArticle'            => App\GraphQL\Mutation\NewArticleMutation::class,
                'editArticle'           => App\GraphQL\Mutation\EditArticleMutation::class,
                'deleteArticle'         => App\GraphQL\Mutation\DeleteArticleMutation::class,
                'toggleArticleFollow'   => App\GraphQL\Mutation\ToggleArticleFollowMutation::class,
                'newFigure'             => App\GraphQL\Mutation\NewArticleFigureMutation::class,
                'editFigure'            => App\GraphQL\Mutation\EditArticleFigureMutation::class,
                'deleteFigure'          => App\GraphQL\Mutation\DeleteArticleFigureMutation::class,
                'newCategory'           => App\GraphQL\Mutation\NewCategoryMutation::class,
                'editCategory'          => App\GraphQL\Mutation\EditCategoryMutation::class,
                'deleteCategory'        => App\GraphQL\Mutation\DeleteCategoryMutation::class,
                'newChallenge'          => App\GraphQL\Mutation\NewChallengeMutation::class,
                'editChallenge'         => App\GraphQL\Mutation\EditChallengeMutation::class,
                'deleteChallenge'       => App\GraphQL\Mutation\DeleteChallengeMutation::class,
                'newComment'            => App\GraphQL\Mutation\NewCommentMutation::class,
                'editComment'           => App\GraphQL\Mutation\EditCommentMutation::class,
                'deleteComment'         => App\GraphQL\Mutation\DeleteCommentMutation::class,
                'toggleLike'            => App\GraphQL\Mutation\ToggleLikeMutation::class,
                'newOrganization'       => App\GraphQL\Mutation\NewOrganizationMutation::class,
                'editOrganization'      => App\GraphQL\Mutation\EditOrganizationMutation::class,
                'deleteOrganization'    => App\GraphQL\Mutation\DeleteOrganizationMutation::class,
                'kick'                  => App\GraphQL\Mutation\KickMutation::class,
                'toggleFollow'          => App\GraphQL\Mutation\ToggleFollowMutation::class,
                'newProject'            => App\GraphQL\Mutation\NewProjectMutation::class,
                'editProject'           => App\GraphQL\Mutation\EditProjectMutation::class,
                'deleteProject'         => App\GraphQL\Mutation\DeleteProjectMutation::class,
                'newPublication'        => App\GraphQL\Mutation\NewPublicationMutation::class,
                'editPublication'       => App\GraphQL\Mutation\EditPublicationMutation::class,
                'deletePublication'     => App\GraphQL\Mutation\DeletePublicationMutation::class,
                'toggleSeal'            => App\GraphQL\Mutation\ToggleSealMutation::class,
                'newSubcategory'        => App\GraphQL\Mutation\NewSubcategoryMutation::class,
                'editSubcategory'       => App\GraphQL\Mutation\EditSubcategoryMutation::class,
                'deleteSubcategory'     => App\GraphQL\Mutation\DeleteSubcategoryMutation::class,
                'editUser'              => App\GraphQL\Mutation\EditUserMutation::class,
                'deleteUser'            => App\GraphQL\Mutation\DeleteUserMutation::class,
            ],
            'middleware' => ['auth:api'],
            'method' => ['post'],
        ],
    ],
    'types' => [
        'user'              => App\GraphQL\Type\UserType::class,
        'organization'      => App\GraphQL\Type\OrganizationType::class,
        'category'          => App\GraphQL\Type\CategoryType::class,
        'subcategory'       => App\GraphQL\Type\SubcategoryType::class,
        'article'           => App\GraphQL\Type\ArticleType::class,
        'article_figure'    => App\GraphQL\Type\ArticleFigureType::class,
        'figure'            => App\GraphQL\Type\FigureObjectType::class,
        'publication'       => App\GraphQL\Type\PublicationType::class,
        'project'           => App\GraphQL\Type\ProjectType::class,
        'challenge'         => App\GraphQL\Type\ChallengeType::class,
        'doc'               => App\GraphQL\Type\DocType::class,
        'seal'              => App\GraphQL\Type\SealType::class,
        'comment'           => App\GraphQL\Type\CommentType::class,
        'like'              => App\GraphQL\Type\LikeType::class,
    ],
    'error_formatter' => ['\Rebing\GraphQL\GraphQL', 'formatError'],
    'errors_handler' => ['\Rebing\GraphQL\GraphQL', 'handleErrors'],
    'params_key'    => 'variables',
    'security' => [
        'query_max_complexity' => null,
        'query_max_depth' => null,
        'disable_introspection' => env('DISABLE_GRAPHQL_INTROSPECTION', false)
    ],
    'pagination_type' => \Rebing\GraphQL\Support\PaginationType::class,
];
